import "../styles/globals.css";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import Providers from "@/utils/Providers";
import { Container, Grid } from "@mui/material";
import { FunctionComponent, PropsWithChildren } from "react";
import Header from "@/components/Common/Header";

const inter = Lato({ weight: ["400", "700", "900"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Stackoverflow Tags",
  description: "Generated by create next app",
};

const RootLayout: FunctionComponent<PropsWithChildren> = ({ children }) => (
  <html lang="en">
    <body className={inter.className}>
      <Providers>
        <Container maxWidth="md">
          <Header />
          <main>
            <Grid container justifyContent="center">
              {children}
            </Grid>
          </main>
        </Container>
      </Providers>
    </body>
  </html>
);

export default RootLayout;
